In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [5]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [6]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [7]:
model= Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

    

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
new

In [9]:
model.get_weights()

[array([[-0.40431613, -1.211189  ],
        [-0.38382196,  0.8067266 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.5813911],
        [-1.1454263]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [12]:
 model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=78,verbose=1,batch_size=1)

Epoch 1/78
4/4 [==============================] - 0s 4ms/step - loss: 100.5586
Epoch 2/78
4/4 [==============================] - 0s 1ms/step - loss: 98.0042
Epoch 3/78
4/4 [==============================] - 0s 2ms/step - loss: 95.2091
Epoch 4/78
4/4 [==============================] - 0s 2ms/step - loss: 93.0558
Epoch 5/78
4/4 [==============================] - 0s 1ms/step - loss: 90.8635
Epoch 6/78
4/4 [==============================] - 0s 1ms/step - loss: 88.5844
Epoch 7/78
4/4 [==============================] - 0s 2ms/step - loss: 86.3958
Epoch 8/78
4/4 [==============================] - 0s 2ms/step - loss: 84.1189
Epoch 9/78
4/4 [==============================] - 0s 1ms/step - loss: 82.2818
Epoch 10/78
4/4 [==============================] - 0s 2ms/step - loss: 80.3121
Epoch 11/78
4/4 [==============================] - 0s 1ms/step - loss: 78.0210
Epoch 12/78
4/4 [==============================] - 0s 2ms/step - loss: 76.4098
Epoch 13/78
4/4 [==============================] - 0s 2ms/st